2018-12-16 18:25:13,706 ERROR: Exception on /simulacia/<name>/<druh>/<vstup> [POST] [in c:\python\tm_final-master\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\python\TM_final-master\app\main\routes.py", line 220, in simulacia
    df,list_of_table,stroj, list_of_tape, length, cycle, final ,cross ,cross_number = table.xntm_table_none_final(name,vstup,final)
  File "C:\python\TM_final-master\table\table.py", line 923, in xntm_table_none_final
    for s,t,c,tape_symbol, current_state,tapes,directions,final, cycle, cross, crossnumber in generator:
  File "C:\python\TM_final-master\turing_machine\xntm.py", line 872, in _validate_input_yield_none_final
    final, cycle, cross, crossnumber = self._validate_input_yieldd_none_final(input_str,zoznam)
  File "C:\python\TM_final-master\turing_machine\xntm.py", line 667, in _validate_input_yieldd_none_final
    tapes[i] = TMTape(self.left_end, blank_symbol=self.blank_symbol)
TypeError: list indices must be integers or slices, not TMTape
2018-12-16 18:25:20,210 ERROR: Exception on /simulacia/<name>/<druh>/<vstup> [POST] [in c:\python\tm_final-master\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\python\TM_final-master\app\main\routes.py", line 220, in simulacia
    df,list_of_table,stroj, list_of_tape, length, cycle, final ,cross ,cross_number = table.xntm_table_none_final(name,vstup,final)
  File "C:\python\TM_final-master\table\table.py", line 923, in xntm_table_none_final
    for s,t,c,tape_symbol, current_state,tapes,directions,final, cycle, cross, crossnumber in generator:
  File "C:\python\TM_final-master\turing_machine\xntm.py", line 872, in _validate_input_yield_none_final
    final, cycle, cross, crossnumber = self._validate_input_yieldd_none_final(input_str,zoznam)
  File "C:\python\TM_final-master\turing_machine\xntm.py", line 667, in _validate_input_yieldd_none_final
    tapes[i] = TMTape(self.left_end, blank_symbol=self.blank_symbol)
TypeError: list indices must be integers or slices, not TMTape
2018-12-16 18:25:25,630 ERROR: Exception on /simulacia/<name>/<druh>/<vstup> [POST] [in c:\python\tm_final-master\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\tm_final-master\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\python\TM_final-master\app\main\routes.py", line 229, in simulacia
    df,list_of_table,stroj, list_of_tape, length, cycle, final ,cross ,cross_number = table.xntm_table_none_final(name,vstup,final)
  File "C:\python\TM_final-master\table\table.py", line 923, in xntm_table_none_final
    for s,t,c,tape_symbol, current_state,tapes,directions,final, cycle, cross, crossnumber in generator:
  File "C:\python\TM_final-master\turing_machine\xntm.py", line 872, in _validate_input_yield_none_final
    final, cycle, cross, crossnumber = self._validate_input_yieldd_none_final(input_str,zoznam)
  File "C:\python\TM_final-master\turing_machine\xntm.py", line 667, in _validate_input_yieldd_none_final
    tapes[i] = TMTape(self.left_end, blank_symbol=self.blank_symbol)
TypeError: list indices must be integers or slices, not TMTape
2018-12-16 19:13:07,730 INFO: Microtm startup [in C:\python\TM_final-master\app\__init__.py:46]
